### ISSUE TITLE
Feature request: Offer more common format

### ISSUE THREAD

**Issue by Avasam** [Helco/Pitfall#1]
Just tried converting the PC version textures and it works! But could some other formats than DirectDraw Surface (DDS) be offered as well? At least some common lossless ones like PNG, bitmap, maybe even webp why not.

DDS are quite unwieldy as they can't be openned with Window's default file viewer, DDS Viewer (found online) has blurry upscaling, Visual Studio takes at least a minute to open (that IDE's so bloated and slow), Photoshop can't open them (maybe with some additional plugin) and finally not all textures are previewable in the File Explorer (see image below)
![image](https://user-images.githubusercontent.com/1350584/226513021-eb01dc9f-8efc-4d2a-a365-965fc332db63.png)

DDS is great for fast Dolphin Texture packs, but a lot harder to work with. Just having integrated PNG support would be enough for me (as they can also be used for Dolphin Texture packs)

**Comment by Helco** [comment]
Sure no problem, DDS was the most lazy way around DXT decoding, but I can add a PNG conversion.

**Comment by Helco** [comment]
Fixed in bfd026a5c4af4f1629f5053f13c873e75ee0c68d
