### ISSUE TITLE
Feature request: Output folder

### ISSUE THREAD

**Issue by Avasam** [Helco/Pitfall#2]
Simple enough, I'd like to be able to dump all the textures somewhere else than "the current folder".

**Comment by Avasam** [comment]
I got confused by the release page that just says `usage: TexConvert.exe [output directory]`. I thought it was weird that the input folder was called output >.<

**Comment by Helco** [comment]
oops, I will fix that release page 👍

**Comment by Avasam** [comment]
Figured it out after looking at the command's help message. I bet the release page probably hid whatever you put in `<>`
