### ISSUE TITLE
[Suggestion] Option to flip output vertically

### ISSUE THREAD

**Issue by Avasam** [Helco/Pitfall#3]
I don't need it, so low priority for me, just an idea that could be useful (if I have the time and motivation I could submit a PR).
Having the output textures immediately flipped (human-usable version) can be a nice-to have for anyone looking to use the textures for other reasons than texture packs.

**Comment by Helco** [comment]
Fixed in a5bf73c

**Comment by Avasam** [comment]
Awesome
